name: 'Setup Node'
description: 'Setup Node and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci
      shell: bash
