name: 'Package'
description: 'Build extension VSIX'

runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Lint
      run: npm run lint
      shell: bash
