name: 'Setup'
description: 'Setup Node and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
      cache: 'npm'

    - name: Install Node dependencies
      run: npm ci
      shell: bash
