name: 'Package'
description: 'Build extension VSIX'

runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Clean README
      run: npm run cleanReadme
      shell: bash

    - name: Build VSIX
      run: npm run package
      shell: bash

    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: VSIX
        path: '*.vsix'
        if-no-files-found: error
        retention-days: 7
